name:
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Enable yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: tuantoquq/portfolio
      IMAGE_TAG: latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - name: Push image
        run: docker push $IMAGE_NAME:$IMAGE_TAG
